l seek 5
h seek -5
j seek -60
k seek 60
S cycle sub
r set play-direction forward
R set play-direction backward
I ab-loop

ALT+t af toggle @rb
ALT+4 af-command rb multiply-pitch 0.9438743126816935
ALT+5 af-command rb set-pitch 1.0
ALT+6 af-command rb multiply-pitch 1.059463094352953
