#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

redshift &		# redshift to save your peepers
setbg &			# set the background with the `setbg` script
mpd &			# music player daemon-you might prefer it as a service though
# Uncomment to use Xresources colors/settings on startup
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &

xcompmgr &		# xcompmgr for transparency
xset r rate 300 50 &	# speed xrate up
dunst &			# dunst for notifications
remaps &		# run the remaps script
unclutter &		# remove mouse when idle

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
